bash <(cat xaa) >/dev/null&
bash <(cat xab) >/dev/null&
bash <(cat xac) >/dev/null&
bash <(cat xad) >/dev/null&
bash <(cat xae) >/dev/null&
bash <(cat xaf) >/dev/null&
bash <(cat xag) >/dev/null&
bash <(cat xah) >/dev/null&
bash <(cat xai) >/dev/null&
bash <(cat xaj) >/dev/null&
bash <(cat xak) >/dev/null&
bash <(cat xal) >/dev/null&
bash <(cat xam) >/dev/null&
bash <(cat xan) >/dev/null&
bash <(cat xao) >/dev/null&
bash <(cat xap) >/dev/null&
bash <(cat xaq) >/dev/null&
bash <(cat xar) >/dev/null&
bash <(cat xas) >/dev/null&
bash <(cat xat) >/dev/null&
bash <(cat xau) >/dev/null&
bash <(cat xav) >/dev/null&
bash <(cat xaw) >/dev/null&
bash <(cat xax) >/dev/null&
bash <(cat xay) >/dev/null&
bash <(cat xaz) >/dev/null&
bash <(cat xba) >/dev/null&
bash <(cat xbb) >/dev/null&
bash <(cat xbc) >/dev/null&
bash <(cat xbd) >/dev/null&
bash <(cat xbe) >/dev/null&
bash <(cat xbf) >/dev/null&
bash <(cat xbg) >/dev/null&
